name: Flutter CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter (3.35.6)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'  # trae Dart 3.9.x

      - name: Show versions
        run: |
          flutter --version
          dart --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze (non-fatal warnings)
        run: dart analyze --no-fatal-warnings

      - name: Run tests
        run: flutter test
