name: Flutter CI & Deploy

on:
  push:
    branches: [ pg-deploy ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter (3.35.6)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'   # Dart 3.9.x
          channel: 'stable'

      - name: Show versions
        run: |
          flutter --version
          dart --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze (warnings allowed)
        run: dart analyze --no-fatal-warnings

      - name: Run tests
        run: flutter test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/pg-deploy'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter (3.35.6)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release --base-href /kidycare-app/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: build/web
